import Ajv from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import addFormats from 'ajv-formats';

/**
 * Ajv's runtime helper for minLength and maxLength (ajv/dist/runtime/ucs2length, MIT), copied so the generated module
 * has no require: it counts characters, with a surrogate pair as one.
 */
export const UCS2LENGTH_SOURCE = `function ucs2length(str) {
  const len = str.length;
  let length = 0;
  let pos = 0;
  let value;
  while (pos < len) {
    length++;
    value = str.charCodeAt(pos++);
    if (value >= 0xd800 && value <= 0xdbff && pos < len) {
      value = str.charCodeAt(pos);
      if ((value & 0xfc00) === 0xdc00) pos++;
    }
  }
  return length;
}`;

const HEADER = `// Generated by scripts/gen-validators.ts from data/schemas. Do not edit: run "npm run gen:validators" in web/.
import { fullFormats } from 'ajv-formats/dist/formats.js';

${UCS2LENGTH_SOURCE}

`;

/**
 * The source of an ES module that exports one precompiled validator per key of `schemas`. Every error is reported
 * (allErrors) and the formats of ajv-formats are used, as the validators built at run time were.
 */
export function generateValidators(schemas: Record<string, object>): string {
  const ajv = new Ajv({ allErrors: true, code: { source: true, esm: true } });
  addFormats(ajv);
  const exports: Record<string, string> = {};
  for (const [name, schema] of Object.entries(schemas)) {
    ajv.addSchema(schema, name);
    exports[name] = name;
  }
  const code = standaloneCode(ajv, exports)
    .replaceAll('require("ajv/dist/runtime/ucs2length").default', 'ucs2length')
    .replaceAll('require("ajv-formats/dist/formats").fullFormats', 'fullFormats');
  const left = code.match(/require\("[^"]*"\)/);
  if (left) throw new Error(`the generated code still has ${left[0]}: add it to the replacements of scripts/lib/validators.ts`);
  return `${HEADER}${code}\n`;
}

/** The type declarations of the generated module. */
export function generateDeclarations(names: readonly string[]): string {
  const lines = names.map((name) => `export const ${name}: Validate;`);
  return `// Generated by scripts/gen-validators.ts. Do not edit.\nimport type { Validate } from './types';\n\n${lines.join('\n')}\n`;
}
