import { describe, it, expect } from 'vitest';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { DATASETS } from '../../src/data/registry';
import { SCENES } from '../../src/types/scene';
import type { Scene } from '../../src/types/scene';

// Vitest runs from web/. The folder is generated by `npm run data:sync` and is never written by this test.
const WEB = process.cwd();
const DATA_DIR = path.join(WEB, 'public', 'data');
const ROOT = path.resolve(WEB, '..');

/**
 * Files in public/data that `sync-data` does not copy, so the manifest does not list them:
 * references.json is written by scripts/build_references.py.
 */
const NOT_IN_MANIFEST = ['references.json'];

/** Scenes that load no dataset today. Each one is a placeholder scene; remove it from here when it loads data. */
const NO_DATA: readonly Scene[] = [
  'andes', // placeholder scene: the campaign events (andes_events.json) are wired in `andes-integration`
  'ai-revolution' // placeholder scene: no dataset yet
];

function requireDataDir(): string {
  if (!fs.existsSync(DATA_DIR)) {
    throw new Error('web/public/data is missing: run npm run data:sync');
  }
  return DATA_DIR;
}

function presentFiles(): string[] {
  return fs
    .readdirSync(requireDataDir())
    .filter((f) => !f.startsWith('_'))
    .sort();
}

function readJson(file: string): unknown {
  return JSON.parse(fs.readFileSync(path.join(requireDataDir(), file), 'utf8'));
}

describe('the data registry', () => {
  it('lists every file once, as a .json name, for known scenes only', () => {
    const files = DATASETS.map((d) => d.file);
    expect(new Set(files).size).toBe(files.length);
    for (const d of DATASETS) {
      expect(d.file).toMatch(/^[a-z0-9_]+\.json$/);
      for (const scene of d.requiredBy) expect(SCENES).toContain(scene);
    }
  });

  it('names the datasets the scenes load today', () => {
    const required = (scene: Scene) => DATASETS.filter((d) => d.requiredBy.includes(scene)).map((d) => d.file).sort();
    expect(required('economy')).toEqual(['economy_series.json']);
    expect(required('resources')).toEqual(['composition.json', 'projects.json', 'resource_production.json']);
    expect(required('forecast')).toEqual(['forecast_output.json']);
    expect(required('sandbox')).toEqual(['forecast_output.json']);
  });

  it('matches what the scene sources actually load with useDataset', () => {
    for (const scene of SCENES) {
      const dir = path.join(WEB, 'src', 'scenes', scene);
      const source = fs
        .readdirSync(dir)
        .filter((f) => f.endsWith('.tsx') || f.endsWith('.ts'))
        .map((f) => fs.readFileSync(path.join(dir, f), 'utf8'))
        .join('\n');
      const loaded = [...source.matchAll(/useDataset\(\s*'([a-z0-9_]+)'/g)].map((m) => `${m[1]}.json`).sort();
      const registered = DATASETS.filter((d) => d.requiredBy.includes(scene)).map((d) => d.file).sort();
      expect(registered, `scene ${scene}`).toEqual([...new Set(loaded)]);
    }
  });
});

describe('web/public/data smoke test', () => {
  it('every file not starting with _ has a registry entry', () => {
    const registered = new Set(DATASETS.map((d) => d.file));
    const unknown = presentFiles().filter((f) => !registered.has(f));
    expect(unknown, `files without a registry entry: ${unknown.join(', ')}`).toEqual([]);
  });

  it('every required file exists; an optional one (no scene requires it) is only parsed when present', () => {
    const present = new Set(presentFiles());
    const missing = DATASETS.filter((d) => d.requiredBy.length > 0 && !present.has(d.file)).map((d) => d.file);
    expect(missing, `required files missing: ${missing.join(', ')}`).toEqual([]);
  });

  it('every present file parses with its parser', () => {
    for (const d of DATASETS) {
      if (!presentFiles().includes(d.file)) continue;
      try {
        d.parse(readJson(d.file));
      } catch (error) {
        throw new Error(`${d.file} does not parse: ${error instanceof Error ? error.message : String(error)}`);
      }
    }
  });

  it('_manifest.json lists exactly the files present, each with origin mock or processed', () => {
    const manifest = readJson('_manifest.json') as { files: { name: string; origin: string }[] };
    const listed = manifest.files.map((f) => f.name).sort();
    const expected = presentFiles().filter((f) => !NOT_IN_MANIFEST.includes(f));
    expect(listed).toEqual(expected);
    for (const f of manifest.files) expect(['mock', 'processed'], `origin of ${f.name}`).toContain(f.origin);
  });

  it('_version.json matches the hash recomputed the way sync-data computes it', () => {
    const manifest = readJson('_manifest.json') as { files: { name: string }[] };
    const concat = manifest.files
      .map((f) => f.name)
      .sort((a, b) => a.localeCompare(b))
      .map((name) => {
        const content = fs.readFileSync(path.join(DATA_DIR, name));
        return `${name}:${crypto.createHash('sha256').update(content).digest('hex')}\n`;
      })
      .join('');
    const expected = crypto.createHash('sha256').update(concat).digest('hex').substring(0, 12);
    expect((readJson('_version.json') as { data_version: string }).data_version).toBe(expected);
  });

  it('every scene has a required dataset or is listed as having none, with its reason', () => {
    for (const scene of SCENES) {
      const hasData = DATASETS.some((d) => d.requiredBy.includes(scene));
      expect(hasData || NO_DATA.includes(scene), `scene ${scene} has no dataset and is not listed in NO_DATA`).toBe(true);
    }
    for (const scene of NO_DATA) {
      expect(DATASETS.some((d) => d.requiredBy.includes(scene)), `${scene} is listed in NO_DATA but loads data`).toBe(false);
    }
  });

  it('the data budget script exits 0', () => {
    const script = path.join(ROOT, 'scripts', 'check_data_budget.py');
    const candidates = process.platform === 'win32' ? ['python'] : ['python3', 'python'];
    const python = candidates.find((c) => spawnSync(c, ['--version']).status === 0);
    expect(python, 'no python interpreter found').toBeDefined();
    const result = spawnSync(python as string, [script, '--dir', requireDataDir()], { encoding: 'utf8' });
    expect(result.status, result.stdout + result.stderr).toBe(0);
  });
});
