// Generated by scripts/gen-validators.ts. Do not edit.
import type { Validate } from './types';

export const aiEstimates: Validate;
export const andesEvents: Validate;
export const baseRates: Validate;
export const composition: Validate;
export const datasetCatalog: Validate;
export const economy: Validate;
export const externalForecasts: Validate;
export const forecast: Validate;
export const forecastVintages: Validate;
export const geoMeta: Validate;
export const population: Validate;
export const productionProjections: Validate;
export const projects: Validate;
export const provincesGeo: Validate;
export const references: Validate;
export const terrainMeta: Validate;
