import ts from 'typescript-eslint';
import jsxA11y from 'eslint-plugin-jsx-a11y';

export default ts.config(
  // generated by scripts/gen-validators.ts (Ajv standalone code); regenerated, never edited, and checked by tests
  { ignores: ['src/validation/generated.js'] },
  ...ts.configs.recommended,
  jsxA11y.flatConfigs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/ban-ts-comment': 'off'
    }
  }
);
